create table person (
	id SERIAL PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    gender VARCHAR(255) NOT NULL
);

create table follower(
    id SERIAL PRIMARY KEY,
    following_user_id INTEGER NOT NULL,
    followed_user_id INTEGER NOT NULL,
    FOREIGN KEY (following_user_id) REFERENCES person (id),
    FOREIGN KEY (followed_user_id) REFERENCES person (id)
);

insert into person (id, first_name, gender) values (1, 'Anton', 'Male');
insert into person (id, first_name, gender) values (2, 'Ofelia', 'Female');
insert into person (id, first_name, gender) values (3, 'Boycey', 'Genderfluid');
insert into person (id, first_name, gender) values (4, 'Ashien', 'Female');
insert into person (id, first_name, gender) values (5, 'Bailie', 'Male');
insert into person (id, first_name, gender) values (6, 'Geoff', 'Male');
insert into person (id, first_name, gender) values (7, 'Celestyn', 'Female');
insert into person (id, first_name, gender) values (8, 'Tommy', 'Male');
insert into person (id, first_name, gender) values (9, 'Riccardo', 'Male');
insert into person (id, first_name, gender) values (10, 'Rurik', 'Male');
insert into person (id, first_name, gender) values (11, 'Doralyn', 'Female');
insert into person (id, first_name, gender) values (12, 'Federica', 'Female');
insert into person (id, first_name, gender) values (13, 'Garv', 'Male');
insert into person (id, first_name, gender) values (14, 'Oswald', 'Male');
insert into person (id, first_name, gender) values (15, 'Cordelia', 'Female');
insert into person (id, first_name, gender) values (16, 'Sigfrid', 'Male');
insert into person (id, first_name, gender) values (17, 'Irma', 'Female');
insert into person (id, first_name, gender) values (18, 'Barn', 'Male');
insert into person (id, first_name, gender) values (19, 'Yanaton', 'Male');
insert into person (id, first_name, gender) values (20, 'Johnette', 'Female');
insert into person (id, first_name, gender) values (21, 'Raye', 'Female');
insert into person (id, first_name, gender) values (22, 'Nelson', 'Male');
insert into person (id, first_name, gender) values (23, 'Reyna', 'Female');
insert into person (id, first_name, gender) values (24, 'Oswell', 'Male');
insert into person (id, first_name, gender) values (25, 'Granville', 'Agender');
insert into person (id, first_name, gender) values (26, 'Brantley', 'Male');
insert into person (id, first_name, gender) values (27, 'Ericka', 'Female');
insert into person (id, first_name, gender) values (28, 'Glenda', 'Female');
insert into person (id, first_name, gender) values (29, 'Lea', 'Female');
insert into person (id, first_name, gender) values (30, 'Deva', 'Female');
insert into person (id, first_name, gender) values (31, 'Dani', 'Male');
insert into person (id, first_name, gender) values (32, 'Kenyon', 'Male');
insert into person (id, first_name, gender) values (33, 'Sophie', 'Female');
insert into person (id, first_name, gender) values (34, 'Kay', 'Female');
insert into person (id, first_name, gender) values (35, 'Byrom', 'Male');
insert into person (id, first_name, gender) values (36, 'Barbabra', 'Agender');
insert into person (id, first_name, gender) values (37, 'Giovanna', 'Female');
insert into person (id, first_name, gender) values (38, 'Bernelle', 'Female');
insert into person (id, first_name, gender) values (39, 'Lewes', 'Male');
insert into person (id, first_name, gender) values (40, 'Gordie', 'Male');
insert into person (id, first_name, gender) values (41, 'Gabbi', 'Female');
insert into person (id, first_name, gender) values (42, 'Veriee', 'Female');
insert into person (id, first_name, gender) values (43, 'Corbett', 'Male');
insert into person (id, first_name, gender) values (44, 'Joye', 'Female');
insert into person (id, first_name, gender) values (45, 'Melisenda', 'Non-binary');
insert into person (id, first_name, gender) values (46, 'Nyssa', 'Female');
insert into person (id, first_name, gender) values (47, 'Caty', 'Female');
insert into person (id, first_name, gender) values (48, 'Barnabas', 'Male');
insert into person (id, first_name, gender) values (49, 'Geralda', 'Female');
insert into person (id, first_name, gender) values (50, 'Decca', 'Male');
insert into person (id, first_name, gender) values (51, 'Oates', 'Genderfluid');
insert into person (id, first_name, gender) values (52, 'Lyssa', 'Female');
insert into person (id, first_name, gender) values (53, 'Foster', 'Male');
insert into person (id, first_name, gender) values (54, 'Shalom', 'Male');
insert into person (id, first_name, gender) values (55, 'Donall', 'Male');
insert into person (id, first_name, gender) values (56, 'Roberta', 'Female');
insert into person (id, first_name, gender) values (57, 'Marybeth', 'Female');
insert into person (id, first_name, gender) values (58, 'Ritchie', 'Male');
insert into person (id, first_name, gender) values (59, 'Husain', 'Male');
insert into person (id, first_name, gender) values (60, 'Zelda', 'Female');
insert into person (id, first_name, gender) values (61, 'Jasmin', 'Female');
insert into person (id, first_name, gender) values (62, 'Dicky', 'Male');
insert into person (id, first_name, gender) values (63, 'Rock', 'Male');
insert into person (id, first_name, gender) values (64, 'Maximilien', 'Male');
insert into person (id, first_name, gender) values (65, 'Fara', 'Female');
insert into person (id, first_name, gender) values (66, 'Ariana', 'Female');
insert into person (id, first_name, gender) values (67, 'Cherin', 'Female');
insert into person (id, first_name, gender) values (68, 'Tann', 'Male');
insert into person (id, first_name, gender) values (69, 'Kristian', 'Male');
insert into person (id, first_name, gender) values (70, 'Ertha', 'Female');
insert into person (id, first_name, gender) values (71, 'Theresina', 'Female');
insert into person (id, first_name, gender) values (72, 'Marlyn', 'Female');
insert into person (id, first_name, gender) values (73, 'Shell', 'Male');
insert into person (id, first_name, gender) values (74, 'Abel', 'Male');
insert into person (id, first_name, gender) values (75, 'Christian', 'Female');
insert into person (id, first_name, gender) values (76, 'Brandtr', 'Male');
insert into person (id, first_name, gender) values (77, 'Abramo', 'Agender');
insert into person (id, first_name, gender) values (78, 'Judye', 'Female');
insert into person (id, first_name, gender) values (79, 'Saundra', 'Female');
insert into person (id, first_name, gender) values (80, 'Berkie', 'Male');
insert into person (id, first_name, gender) values (81, 'Mace', 'Male');
insert into person (id, first_name, gender) values (82, 'Lira', 'Female');
insert into person (id, first_name, gender) values (83, 'Brion', 'Male');
insert into person (id, first_name, gender) values (84, 'Park', 'Male');
insert into person (id, first_name, gender) values (85, 'Fanya', 'Female');
insert into person (id, first_name, gender) values (86, 'Butch', 'Male');
insert into person (id, first_name, gender) values (87, 'Bonnibelle', 'Female');
insert into person (id, first_name, gender) values (88, 'Chadd', 'Genderqueer');
insert into person (id, first_name, gender) values (89, 'Marlo', 'Genderfluid');
insert into person (id, first_name, gender) values (90, 'Domenic', 'Male');
insert into person (id, first_name, gender) values (91, 'Karney', 'Male');
insert into person (id, first_name, gender) values (92, 'Anne-corinne', 'Female');
insert into person (id, first_name, gender) values (93, 'Niko', 'Male');
insert into person (id, first_name, gender) values (94, 'Wernher', 'Male');
insert into person (id, first_name, gender) values (95, 'Obed', 'Male');
insert into person (id, first_name, gender) values (96, 'Delinda', 'Female');
insert into person (id, first_name, gender) values (97, 'Charita', 'Non-binary');
insert into person (id, first_name, gender) values (98, 'Clareta', 'Genderfluid');
insert into person (id, first_name, gender) values (99, 'Mariam', 'Female');
insert into person (id, first_name, gender) values (100, 'Monica', 'Female');
insert into person (id, first_name, gender) values (101, 'Pierson', 'Male');
insert into person (id, first_name, gender) values (102, 'Sukey', 'Female');
insert into person (id, first_name, gender) values (103, 'Cristina', 'Female');
insert into person (id, first_name, gender) values (104, 'Amye', 'Female');
insert into person (id, first_name, gender) values (105, 'Amata', 'Female');
insert into person (id, first_name, gender) values (106, 'Arlen', 'Male');
insert into person (id, first_name, gender) values (107, 'Vite', 'Male');
insert into person (id, first_name, gender) values (108, 'Selena', 'Female');
insert into person (id, first_name, gender) values (109, 'Wini', 'Female');
insert into person (id, first_name, gender) values (110, 'Hy', 'Male');
insert into person (id, first_name, gender) values (111, 'Udall', 'Male');
insert into person (id, first_name, gender) values (112, 'Prudy', 'Female');
insert into person (id, first_name, gender) values (113, 'Ivan', 'Male');
insert into person (id, first_name, gender) values (114, 'Aldus', 'Male');
insert into person (id, first_name, gender) values (115, 'Rob', 'Male');
insert into person (id, first_name, gender) values (116, 'Alysa', 'Female');
insert into person (id, first_name, gender) values (117, 'Marcus', 'Male');
insert into person (id, first_name, gender) values (118, 'Bennett', 'Male');
insert into person (id, first_name, gender) values (119, 'Marty', 'Male');
insert into person (id, first_name, gender) values (120, 'Chane', 'Male');
insert into person (id, first_name, gender) values (121, 'Bryant', 'Male');
insert into person (id, first_name, gender) values (122, 'Linnet', 'Female');
insert into person (id, first_name, gender) values (123, 'Elvin', 'Male');
insert into person (id, first_name, gender) values (124, 'Kurtis', 'Male');
insert into person (id, first_name, gender) values (125, 'Doyle', 'Male');
insert into person (id, first_name, gender) values (126, 'Natalya', 'Female');
insert into person (id, first_name, gender) values (127, 'Julius', 'Male');
insert into person (id, first_name, gender) values (128, 'Silvie', 'Female');
insert into person (id, first_name, gender) values (129, 'Darnell', 'Male');
insert into person (id, first_name, gender) values (130, 'Wini', 'Genderfluid');
insert into person (id, first_name, gender) values (131, 'Quintus', 'Male');
insert into person (id, first_name, gender) values (132, 'Padget', 'Non-binary');
insert into person (id, first_name, gender) values (133, 'Herby', 'Male');
insert into person (id, first_name, gender) values (134, 'Kalinda', 'Female');
insert into person (id, first_name, gender) values (135, 'Jone', 'Agender');
insert into person (id, first_name, gender) values (136, 'Roobbie', 'Female');
insert into person (id, first_name, gender) values (137, 'Biddy', 'Female');
insert into person (id, first_name, gender) values (138, 'Dulsea', 'Female');
insert into person (id, first_name, gender) values (139, 'Archy', 'Male');
insert into person (id, first_name, gender) values (140, 'Darrelle', 'Female');
insert into person (id, first_name, gender) values (141, 'Rufus', 'Non-binary');
insert into person (id, first_name, gender) values (142, 'Rikki', 'Male');
insert into person (id, first_name, gender) values (143, 'Reg', 'Male');
insert into person (id, first_name, gender) values (144, 'Jamey', 'Male');
insert into person (id, first_name, gender) values (145, 'Joela', 'Female');
insert into person (id, first_name, gender) values (146, 'Helli', 'Female');
insert into person (id, first_name, gender) values (147, 'Ondrea', 'Female');
insert into person (id, first_name, gender) values (148, 'Carole', 'Female');
insert into person (id, first_name, gender) values (149, 'Erhard', 'Male');
insert into person (id, first_name, gender) values (150, 'Jilli', 'Female');
insert into person (id, first_name, gender) values (151, 'Malva', 'Polygender');
insert into person (id, first_name, gender) values (152, 'Brenden', 'Male');
insert into person (id, first_name, gender) values (153, 'Nicolas', 'Male');
insert into person (id, first_name, gender) values (154, 'Ibby', 'Genderqueer');
insert into person (id, first_name, gender) values (155, 'Jerrold', 'Male');
insert into person (id, first_name, gender) values (156, 'Larisa', 'Female');
insert into person (id, first_name, gender) values (157, 'Dewain', 'Male');
insert into person (id, first_name, gender) values (158, 'Mendie', 'Male');
insert into person (id, first_name, gender) values (159, 'Toma', 'Female');
insert into person (id, first_name, gender) values (160, 'Blake', 'Female');
insert into person (id, first_name, gender) values (161, 'David', 'Male');
insert into person (id, first_name, gender) values (162, 'Orson', 'Male');
insert into person (id, first_name, gender) values (163, 'Vyky', 'Female');
insert into person (id, first_name, gender) values (164, 'Rriocard', 'Male');
insert into person (id, first_name, gender) values (165, 'Alix', 'Male');
insert into person (id, first_name, gender) values (166, 'Joeann', 'Female');
insert into person (id, first_name, gender) values (167, 'Patience', 'Non-binary');
insert into person (id, first_name, gender) values (168, 'Izaak', 'Male');
insert into person (id, first_name, gender) values (169, 'Salomi', 'Female');
insert into person (id, first_name, gender) values (170, 'Nancee', 'Polygender');
insert into person (id, first_name, gender) values (171, 'Cordelia', 'Female');
insert into person (id, first_name, gender) values (172, 'Augustus', 'Male');
insert into person (id, first_name, gender) values (173, 'Ichabod', 'Male');
insert into person (id, first_name, gender) values (174, 'Freemon', 'Male');
insert into person (id, first_name, gender) values (175, 'Buiron', 'Male');
insert into person (id, first_name, gender) values (176, 'Tobi', 'Female');
insert into person (id, first_name, gender) values (177, 'Royall', 'Male');
insert into person (id, first_name, gender) values (178, 'Bogart', 'Male');
insert into person (id, first_name, gender) values (179, 'Reena', 'Female');
insert into person (id, first_name, gender) values (180, 'Welby', 'Male');
insert into person (id, first_name, gender) values (181, 'Caesar', 'Male');
insert into person (id, first_name, gender) values (182, 'Fleming', 'Male');
insert into person (id, first_name, gender) values (183, 'Avril', 'Female');
insert into person (id, first_name, gender) values (184, 'Byram', 'Male');
insert into person (id, first_name, gender) values (185, 'Ab', 'Male');
insert into person (id, first_name, gender) values (186, 'Gideon', 'Male');
insert into person (id, first_name, gender) values (187, 'Tracie', 'Male');
insert into person (id, first_name, gender) values (188, 'Cathe', 'Female');
insert into person (id, first_name, gender) values (189, 'Kati', 'Female');
insert into person (id, first_name, gender) values (190, 'Durward', 'Male');
insert into person (id, first_name, gender) values (191, 'Donaugh', 'Polygender');
insert into person (id, first_name, gender) values (192, 'Derick', 'Male');
insert into person (id, first_name, gender) values (193, 'Hallsy', 'Male');
insert into person (id, first_name, gender) values (194, 'Lyndsie', 'Female');
insert into person (id, first_name, gender) values (195, 'Guillaume', 'Male');
insert into person (id, first_name, gender) values (196, 'Celina', 'Female');
insert into person (id, first_name, gender) values (197, 'Domeniga', 'Female');
insert into person (id, first_name, gender) values (198, 'Dunstan', 'Male');
insert into person (id, first_name, gender) values (199, 'Ashia', 'Female');
insert into person (id, first_name, gender) values (200, 'Carlee', 'Female');

insert into follower (following_user_id, followed_user_id) values (7,1);
insert into follower (following_user_id, followed_user_id) values (7,2);
insert into follower (following_user_id, followed_user_id) values (7,3);
insert into follower (following_user_id, followed_user_id) values (7,4);
insert into follower (following_user_id, followed_user_id) values (7,5);
insert into follower (following_user_id, followed_user_id) values (7,6);
insert into follower (following_user_id, followed_user_id) values (7,7);
insert into follower (following_user_id, followed_user_id) values (7,8);
insert into follower (following_user_id, followed_user_id) values (7,9);
insert into follower (following_user_id, followed_user_id) values (7,10);
insert into follower (following_user_id, followed_user_id) values (7,11);
insert into follower (following_user_id, followed_user_id) values (7,12);

insert into follower (following_user_id, followed_user_id) values (3,4);
insert into follower (following_user_id, followed_user_id) values (3,5);
insert into follower (following_user_id, followed_user_id) values (3,6);
insert into follower (following_user_id, followed_user_id) values (3,7);
insert into follower (following_user_id, followed_user_id) values (3,8);
insert into follower (following_user_id, followed_user_id) values (3,9);
insert into follower (following_user_id, followed_user_id) values (3,10);
insert into follower (following_user_id, followed_user_id) values (3,11);

insert into follower (following_user_id, followed_user_id) values (8,3);
insert into follower (following_user_id, followed_user_id) values (3,7);
insert into follower (following_user_id, followed_user_id) values (3,22);
insert into follower (following_user_id, followed_user_id) values (3,44);
insert into follower (following_user_id, followed_user_id) values (3,37);
insert into follower (following_user_id, followed_user_id) values (3,21);
insert into follower (following_user_id, followed_user_id) values (3,86);
insert into follower (following_user_id, followed_user_id) values (3,24);
insert into follower (following_user_id, followed_user_id) values (3,11);


insert into follower (following_user_id, followed_user_id) values (15,4);
insert into follower (following_user_id, followed_user_id) values (15,5);
insert into follower (following_user_id, followed_user_id) values (15,6);
insert into follower (following_user_id, followed_user_id) values (15,7);
insert into follower (following_user_id, followed_user_id) values (15,8);
insert into follower (following_user_id, followed_user_id) values (15,9);
insert into follower (following_user_id, followed_user_id) values (15,10);
insert into follower (following_user_id, followed_user_id) values (15,11);



insert into follower (following_user_id, followed_user_id) values (18,4);
insert into follower (following_user_id, followed_user_id) values (18,5);
insert into follower (following_user_id, followed_user_id) values (18,6);
insert into follower (following_user_id, followed_user_id) values (18,7);
insert into follower (following_user_id, followed_user_id) values (18,8);
insert into follower (following_user_id, followed_user_id) values (18,9);
insert into follower (following_user_id, followed_user_id) values (18,10);
insert into follower (following_user_id, followed_user_id) values (18,76);
insert into follower (following_user_id, followed_user_id) values (18,77);
insert into follower (following_user_id, followed_user_id) values (18,78);
insert into follower (following_user_id, followed_user_id) values (18,81);
insert into follower (following_user_id, followed_user_id) values (18,104);
insert into follower (following_user_id, followed_user_id) values (18,121);
insert into follower (following_user_id, followed_user_id) values (18,122);
insert into follower (following_user_id, followed_user_id) values (18,165);

insert into follower (following_user_id, followed_user_id) values (65,4);
insert into follower (following_user_id, followed_user_id) values (65,5);
insert into follower (following_user_id, followed_user_id) values (65,6);
insert into follower (following_user_id, followed_user_id) values (65,7);
insert into follower (following_user_id, followed_user_id) values (65,8);
insert into follower (following_user_id, followed_user_id) values (65,9);
insert into follower (following_user_id, followed_user_id) values (65,10);
insert into follower (following_user_id, followed_user_id) values (65,11);
